server:
   port: 8080
spring:
   application:
      name: message-exchange
   datasource:
      url: jdbc:mysql://localhost:3306/message?createDatabaseIfNotExist=true
      username: root
      password: password
   jpa:
      hibernate.ddl-auto: create-drop
      generate-ddl: true
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect